name: 📑 Release Page

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: 📑 Release Page
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v6

      - name: 📑 Release Page
        uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          make_latest: true
